### get products
get http://localhost:3000/products/

### get products by id
get http://localhost:3000/products/apcj6tclbfhqung3

### post products
post http://localhost:3000/products/
Content-Type: application/json

{
    "name": "Á66",
    "quantity": 24,
    "price": 6500,
    "type": "fémáru"
}

### delete products by id
delete http://localhost:3000/products/e8vxk41mslda2dm0y

### put products by id
put http://localhost:3000/products/apcj1q8lbfnah5m
Content-Type: application/json

{
    "name": "Á1",
    "quantity": 24,
    "price": 2500,
    "type": "tejtermék"
}